import { Geist, Geist_Mono, Prata } from "next/font/google";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "./_components/AppSidebar";
import {ClerkProvider} from '@clerk/nextjs'
import Provider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const prata = Prata({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-prata',
})

export const metadata = {
  title: "Astrai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${prata.variable} antialiased`}
        >
          <SidebarProvider>
              <AppSidebar />
              <SidebarTrigger />
              <Provider>
                {children}
              </Provider>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
